sudo: required
services:
   - docker



env:
  global:
# Do not prompt for user input when using any SDK methods.
    - CLOUDSDK_CORE_DISABLE_PROMPTS=1
#Installing Google SDK:
before_install:
   - openssl aes-256-cbc -K $encrypted_0c35eebf403c_key -iv $encrypted_0c35eebf403c_iv -in service-account.json.enc -out service-account.json -d
   - if [ ! -d "$HOME/google-cloud-sdk/bin" ]; then rm -rf "$HOME/google-cloud-sdk"; curl https://sdk.cloud.google.com | bash > /dev/null; fi
# The install script errors if this directory already exists,
# but Travis already creates it when we mark it as cached.
# The install script is overly verbose, which sometimes causes
# problems on Travis, so ignore stdout.
# This line is critical. We setup the SDK to take precedence in our
# environment over the old SDK that is already on the machine.
   - source $HOME/google-cloud-sdk/path.bash.inc
   - gcloud components update kubectl
   - gcloud auth activate-service-account --key-file service-account.json
   - gcloud config set project e-minutia-231605
   - gcloud config set compute/zone europe-north1-a
   - gcloud container clusters get-credentials elk
   - echo "before install ended"
script:
   - pwd
   - echo "script section ended"
deploy:
  provider: script
  script: bash ./deploy.sh
  on:
     branch: master