apiVersion: v1
kind: Service
metadata:
   name: elasticsearch
spec:
   type: ClusterIP #internal network
   ports:
      - port: 9200
        targetPort: 9200
        name: port-9200
      - port: 9300
        targetPort: 9300
        name: port-9300
   selector:
      component: elasticsearch
