apiVersion: apps/v1
kind: Deployment
metadata:
   name: elastic-deployment
spec:
   replicas: 1
   selector:
      matchLabels:
         component: elasticsearch
   template:
      metadata:
          labels:
              component: elasticsearch
      spec:
         volumes:
            - name: data
              persistentVolumeClaim:
                 claimName: elasticsearch-data
         initContainers:
            - name: increase-the-vm-max-map-count
              image: busybox
              command:
              - sysctl
              - -w
              - vm.max_map_count=262144
              securityContext:
                 privileged: true
            - name: fix-the-volume-permission
              image: busybox
              command:
              - sh
              - -c
              - chown -R 1000:1000 /usr/share/elasticsearch/data
              securityContext:
                 privileged: true
              volumeMounts:
              - name: data
                mountPath: /usr/share/elasticsearch/data
            - name: increase-the-ulimit
              image: busybox
              command:
              - sh
              - -c
              - ulimit -n 65536
              securityContext:
                privileged: true
            - name: check-elastic-rights
              image: busybox
              command:
              - ls
              securityContext:
                privileged: true
              volumeMounts:
              - name: data
                mountPath: /usr/share/elasticsearch/data
         containers:
            - name: elasticsearch
              image: docker.elastic.co/elasticsearch/elasticsearch:6.5.4
              ports:
                 - containerPort: 9200
                 - containerPort: 9300
              volumeMounts:
                 - name: data
                   mountPath: /usr/share/elasticsearch/data
                   subPath: es-data
